In [892]:
import pandas as pd
import numpy as np
import re 
from scipy import stats

# 1. Get General from Df

In [893]:
# The file presented this Error: utf-8' codec can't decode byte 0xa0 in position 698: invalid start byte
#encoding = 'utf8' was tried without success

df = pd.read_csv('/Users/chuy/Documents/project-pandas/attacks.csv',  encoding = 'latin1')

df.head().T

,0,1,2,3,4
Case Number,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04
Date,25-Jun-2018,18-Jun-2018,09-Jun-2018,08-Jun-2018,04-Jun-2018
Year,2018.0,2018.0,2018.0,2018.0,2018.0
Type,Boating,Unprovoked,Invalid,Unprovoked,Provoked
Country,USA,USA,USA,AUSTRALIA,MEXICO
Area,California,Georgia,Hawaii,New South Wales,Colima
Location,"Oceanside, San Diego County","St. Simon Island, Glynn County","Habush, Oahu",Arrawarra Headland,La Ticla
Activity,Paddling,Standing,Surfing,Surfing,Free diving
Name,Julie Wolfe,AdysonÂ McNeely,John Denges,male,Gustavo Ramos
Sex,F,F,M,M,M
Age,57,11,48,NaN,NaN
Injury,"No injury to occupant, outrigger canoe and pad...",Minor injury to left thigh,Injury to left lower leg from surfboard skeg,Minor injury to lower leg,Lacerations to leg & hand shark PROVOKED INCIDENT
Fatal (Y/N),N,N,N,N,N
Time,18h00,14h00 -15h00,07h45,NaN,NaN
Species,White shark,NaN,NaN,2 m shark,"Tiger shark, 3m"
Investigator or Source,"R. Collier, GSAF","K.McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","B. Myatt, GSAF",A .Kipper
pdf,2018.06.25-Wolfe.pdf,2018.06.18-McNeely.pdf,2018.06.09-Denges.pdf,2018.06.08-Arrawarra.pdf,2018.06.04-Ramos.pdf
href formula,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
Case Number.1,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04
Case Number.2,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04
original order,6303.0,6302.0,6301.0,6300.0,6299.0
Unnamed: 22,NaN,NaN,NaN,NaN,NaN
Unnamed: 23,NaN,NaN,NaN,NaN,NaN

In [894]:
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [895]:
df.columns = df.columns.str.strip()
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [896]:
df.shape

(25723, 24)

In [897]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [898]:
df.isnull().sum()/df.shape[0]

Case Number               0.661704
Date                      0.755005
Year                      0.755083
Type                      0.755161
Country                   0.756949
Area                      0.772694
Location                  0.775998
Activity                  0.776154
Name                      0.763169
Sex                       0.776970
Age                       0.865062
Injury                    0.756094
Fatal (Y/N)               0.775959
Time                      0.885394
Species                   0.865335
Investigator or Source    0.755666
pdf                       0.755005
href formula              0.755044
href                      0.755005
Case Number.1             0.755005
Case Number.2             0.755005
original order            0.754733
Unnamed: 22               0.999961
Unnamed: 23               0.999922
dtype: float64

# 2. Extreme Cleaning : Useless Columns and Duplicated Info

In [899]:
# All the columns have a percentage of null values above of 25%
# Columns Unamed: 22 and Unamed 23 are almost 100% full of null values, with the exception of: 

df[(df['Unnamed: 22'].isnull()==False)+(df['Unnamed: 23'].isnull()==False)].T

,1478,4415,5840
Case Number,2006.05.27,1952.03.30,1878.09.14.R
Date,27-May-2006,30-Mar-1952,Reported 14-Sep-1878
Year,2006.0,1952.0,1878.0
Type,Unprovoked,Unprovoked,Provoked
Country,USA,NETHERLANDS ANTILLES,USA
Area,Hawaii,Curacao,Connecticut
Location,"North Shore, O'ahu",NaN,"Branford, New Haven County"
Activity,Surfing,Went to aid of child being menaced by the shark,Fishing
Name,Bret Desmond,A.J. Eggink,Captain Pattison
Sex,M,M,M
Age,31,NaN,NaN
Injury,"No injury, shark bumped surfboard","Buttock bitten, tissue removed",Leg bitten by netted shark PROVOKED INCIDENT
Fatal (Y/N),N,N,N
Time,16h00,NaN,NaN
Species,NaN,"Bull shark, 2.7 m [9'] was captured & dragged ...",NaN
Investigator or Source,R. Collier,"J. Randall, p.352 in Sharks & Survival; H.D. B...","St. Joseph Herald, 9/14/1878"
pdf,2006.05.27-Desmond.pdf,1952.03.30-Eggink.pdf,1878.09.14.R-Pattison.pdf
href formula,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
Case Number.1,2006.05.27,1952.03.30,1878.09.14.R
Case Number.2,2006.05.27,1952.03.30,1878.09.14.R
original order,4825.0,1888.0,463.0
Unnamed: 22,stopped here,NaN,NaN
Unnamed: 23,NaN,Teramo,change filename

### Drop columns with 99% of null values

In [900]:
#no representative values were found, they will be removed.

df.drop(['Unnamed: 22', 'Unnamed: 23'], axis = 1, inplace = True)

In [901]:
df.shape

(25723, 22)

In [902]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
dtypes: float64(2), object(20)
memory usage: 4.3+ MB

### Duplicated Info Columns

In [903]:
df.head(4).T

,0,1,2,3
Case Number,2018.06.25,2018.06.18,2018.06.09,2018.06.08
Date,25-Jun-2018,18-Jun-2018,09-Jun-2018,08-Jun-2018
Year,2018.0,2018.0,2018.0,2018.0
Type,Boating,Unprovoked,Invalid,Unprovoked
Country,USA,USA,USA,AUSTRALIA
Area,California,Georgia,Hawaii,New South Wales
Location,"Oceanside, San Diego County","St. Simon Island, Glynn County","Habush, Oahu",Arrawarra Headland
Activity,Paddling,Standing,Surfing,Surfing
Name,Julie Wolfe,AdysonÂ McNeely,John Denges,male
Sex,F,F,M,M
Age,57,11,48,NaN
Injury,"No injury to occupant, outrigger canoe and pad...",Minor injury to left thigh,Injury to left lower leg from surfboard skeg,Minor injury to lower leg
Fatal (Y/N),N,N,N,N
Time,18h00,14h00 -15h00,07h45,NaN
Species,White shark,NaN,NaN,2 m shark
Investigator or Source,"R. Collier, GSAF","K.McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","B. Myatt, GSAF"
pdf,2018.06.25-Wolfe.pdf,2018.06.18-McNeely.pdf,2018.06.09-Denges.pdf,2018.06.08-Arrawarra.pdf
href formula,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
Case Number.1,2018.06.25,2018.06.18,2018.06.09,2018.06.08
Case Number.2,2018.06.25,2018.06.18,2018.06.09,2018.06.08
original order,6303.0,6302.0,6301.0,6300.0

In [904]:
df.loc[(df['Case Number'] != df['Case Number.1']) | (df['Case Number'] != df['Case Number.2']) | (df['Case Number.1'] != df['Case Number.2'])]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
34,2018.04.03,03-Apr-2018,2018.0,Unprovoked,SOUTH AFRICA,Eastern Cape Province,St. Francis Bay,Surfing,Ross Spowart,M,...,N,15h00,White shark,"K. McMurray, TrackingSharks.com",2018.04.03-StFrancisBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.02,2018.04.03,6269.0
117,2017.07.20.a,20-Jul-2017,2017.0,Unprovoked,USA,California,"Seal Rock, Goleta Beach, Santa Barbara",SUP,Rolf Geyling,M,...,N,07h45,"White shark, 8' to 10'","R. Collier, GSAF",2017.07.20.a-Geyling.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017/07.20.a,2017.07.20.a,6186.0
144,2017.05.06,05-May-2017,2017.0,Unprovoked,MEXICO,Baja California Sur,"Los Arbolitos, Cabo Pulmo",Snorkeling,Andres Rozada,M,...,Y,17h00,NaN,J. Rozada,2017.05.06-Rozada.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.06,2017.05.06,6159.0
217,2016.09.15,16-Sep-2016,2016.0,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,6086.0
314,2016.01.24.b,24-Jan-2016,2016.0,Unprovoked,USA,Texas,Off Surfside,Spearfishing,Keith Love,M,...,N,09h30 / 10h00,Bull sharks x 2,K. Love,2016.01.24.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.01.24.b,2016.01.24.b,5989.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [905]:
df[df['Case Number'] != df['Case Number.1']]['Case Number'][217]

'2016.09.15'

In [906]:
df[df['Case Number'] != df['Case Number.1']]['Case Number.1'][217]

'2016.09.16'

In [907]:
df[df['Case Number'] != df['Case Number.1']]['Case Number.2'][217]

'2016.09.15'

In [908]:
# In case Case Number have some null values, Case Number 1 and 2. will fill them

In [909]:
df['Case Number'] = df['Case Number'].fillna(df['Case Number.1'])

In [910]:
df['Case Number'] = df['Case Number'].fillna(df['Case Number.2'])

In [911]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8703 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
dtypes: float64(2), object(20)
memory usage: 4.3+ MB

In [912]:
df.loc[(df['href'] != df['href formula'])]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order
50,2018.01.13,13-Jan-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Martin Islet,Free diving,Callum Stewart,M,...,N,NaN,"White shark, 3.5 m","B. Myatt, GSAF",2018.01.13-Stewart.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.01.13,2018.01.13,6253.0
96,2017.08.29,29-Aug-2017,2017.0,Unprovoked,AUSTRALIA,Victoria,Cathedral Rock,Surfing,Marcel Brundler,M,...,N,10h30,"White shark, 3 m","B. Myatt, GSAF",2017.08.27-Brundler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.29,2017.08.29,6207.0
131,2017.06.05,2017.06.05,2017.0,Unprovoked,FRENCH POLYNESIA,Marquesas,"Atuona Bay, Hiva Oa Island",Surfing,male,M,...,N,NaN,NaN,"Tahiti Infos, 6/6/2017",2017.06.05-FrenchPolynesia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.05,2017.06.05,6172.0
133,2017.06.11,11-Jun-2017,2017.0,Unprovoked,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,...,N,08h30,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.11,2017.06.11,6170.0
141,2017.05.27,27-May-2017,2017.0,Invalid,AUSTRALIA,New South Wales,Evans Head,Fishing,Terry Selwood,M,...,N,NaN,NaN,"B. Myatt, GSAF",2017.05.27-Selwood.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.05.27,2017.05.27,6162.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [913]:
df.shape

(25723, 22)

In [914]:
df[df['href'] != df['href formula']]['href formula'][96]

'http://sharkattackfile.net/spreadsheets/pdf_directory/2017.08.27-Brundler.pdf'

In [915]:
df[df['href'] != df['href formula']]['href'][96]

'http://sharkattackfile.net/spreadsheets/pdf_directory/http://sharkattackfile.net/spreadsheets/pdf_directory/2017.08.27-Brundler.pdf'

In [916]:
df[df['href'] != df['href formula']]['href'][96].split('/h')[-1]

'ttp://sharkattackfile.net/spreadsheets/pdf_directory/2017.08.27-Brundler.pdf'

In [917]:
df[df['href'] != df['href formula']]['href'][141].split('/http')[-1]

'://sharkattackfile.net/spreadsheets/pdf_directory/2017.05.27-Selwood.pdf'

In [918]:
# Get values from href fromula to href

In [919]:
df['href'] = df['href'].fillna(df['href formula'])

In [920]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8703 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
dtypes: float64(2), object(20)
memory usage: 4.3+ MB

In [921]:
# drop columns: Case Number 1., Case Number.2 and href formula

In [922]:
df.drop(['Case Number.1','Case Number.2','href formula'],axis=1,inplace=True)

In [923]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8703 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href                    6302 non-null   object
 18  original order          6309 non-null   float64
dtypes: float64(2), object(17)
memory usage: 3.7+ MB

In [924]:
df[df.isna().any(axis=1)]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href,original order
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,NaN,"No injury, board bitten",N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6298.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Kill Rows

In [930]:
df.dropna(how='all', inplace=True)

In [931]:
df.shape

(8703, 19)

In [932]:
df.tail()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href,original order
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [847]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8703 entries, 0 to 25722
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8703 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href                    6302 non-null   object
 18  original order          6309 non-null   float64
dtypes: float64(2), object(17)
memory usage: 1.3+ MB

# 3. Remaining Columns Cleaning

In [868]:
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0

### Case Number

In [933]:
df.tail(10)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href,original order
8693,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8694,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8695,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8696,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8697,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [850]:
df['Case Number'].unique()

array(['2018.06.25', '2018.06.18', '2018.06.09', ..., 'ND.0001', '0',
       'xx'], dtype=object)

In [674]:
#se buscaba remover .a, .b pero se consdera info para Case Number
#remove_letters =lambda x:re.sub('.[a-z]|.[A-Z]','',str(x)).strip()

In [675]:
# REmove letters at the end of the Case Numbers
#def remove_letters(x):
    #r = r'.[a-z]|.[A-Z]'
    #for x in df['Case Number'].unique():
        #if r in x:
            #return re.sub('.[a-z]|.[A-Z]','',str(x)).strip() 
        #else:
            #return x

In [676]:
#df['Case Number'] = df['Case Number'].apply(remove_letters)

In [869]:
df.head(15)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,NaN,"No injury, board bitten",N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6298.0
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6297.0
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,52,Minor injury to foot. PROVOKED INCIDENT,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6296.0
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,Lower left leg bitten,N,17h00,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6295.0
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,12,Minor injury to foot,N,14h00,NaN,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6294.0
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6293.0
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,Trey de Boer,M,10,Injuries to lower right leg and foot,N,NaN,NaN,"C. Creswell, GSAF",2018.05.21-deBoer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6292.0
12,2018.05.13.b,13-May-2018,2018.0,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,10,Severe bite to right forearm,N,15h00,NaN,"C. Creswell, GSAF & K. McMurray TrackingSharks...",2018.05.13.b-Turrell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6291.0
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,Injured by teeth of a dead porbeagle shark he ...,N,08h15,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6290.0
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,34,Shallow lacerations to finger PROVOKED INCIDENT,N,NaN,"Tawny nurse shark, 2m","Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6289.0

In [678]:
#[re.sub('.[a-z]|.[A-Z]','',str(x)).strip() for x in df['Case Number'].unique()]

In [945]:
# Every missing value = NaN
def fill_in(x):
    if not re.findall('\d',str(x)):
        return np.NaN
    elif x == '0':
        return np.NaN
    
    else:
        return x

In [948]:
# KILL MORE ROWS!
df.dropna(how='all', inplace=True)

In [949]:
#biutiful
df.shape

(6309, 19)

In [946]:
df['Case Number']=df['Case Number'].apply(fill_in)

In [ ]:
#Eliminar mas rows

In [950]:
df.tail(10).T

,6299,6300,6301,6302,6303,6304,6305,6306,6307,6308
Case Number,ND.0003,ND.0002,ND.0001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Date,1900-1905,1883-1889,1845-1853,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Type,Unprovoked,Unprovoked,Unprovoked,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,USA,PANAMA,CEYLON (SRI LANKA),NaN,NaN,NaN,NaN,NaN,NaN,NaN
Area,North Carolina,NaN,Eastern Province,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Location,Ocracoke Inlet,"Panama Bay 8ÂºN, 79ÂºW","Below the English fort, Trincomalee",NaN,NaN,NaN,NaN,NaN,NaN,NaN
Activity,Swimming,NaN,Swimming,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Name,Coast Guard personnel,Jules Patterson,male,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sex,M,M,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Injury,FATAL,FATAL,"FATAL. ""Shark bit him in half, carrying away t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fatal (Y/N),Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Species,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Investigator or Source,"F. Schwartz, p.23; C. Creswell, GSAF","The Sun, 10/20/1938",S.W. Baker,NaN,NaN,NaN,NaN,NaN,NaN,NaN
pdf,ND-0003-Ocracoke_1900-1905.pdf,ND-0002-JulesPatterson.pdf,ND-0001-Ceylon.pdf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
original order,4.0,3.0,2.0,6304.0,6305.0,6306.0,6307.0,6308.0,6309.0,6310.0

In [682]:
df['Case Number'].unique()

array(['2018.06.25', '2018.06.18', '2018.06.09', ..., '.0001', '0', nan],
      dtype=object)

### Date

In [951]:
df['Date'].unique()

array(['25-Jun-2018', '18-Jun-2018', '09-Jun-2018', ..., '1883-1889',
       '1845-1853', nan], dtype=object)

In [873]:
#to_date =lambda x:re.sub('.[a-z]|.[A-Z]','',str(x)).strip()

In [952]:
df['Date'].head(30)

0              25-Jun-2018
1              18-Jun-2018
2              09-Jun-2018
3              08-Jun-2018
4              04-Jun-2018
5              03-Jun-2018
6              03-Jun-2018
7              27-May-2018
8              26-May-2018
9              26-May-2018
10             24-May-2018
11             21-May-2018
12             13-May-2018
13             13-May-2018
14                May 2018
15             12-May-2018
16             09-May-2018
17    Reported 30-Apr-2018
18             28-Apr-2018
19             28-Apr-2018
20             25-Apr-2018
21             25-Apr-2018
22             24-Apr-2018
23             23-Apr-2018
24             22-Apr-2018
25             19-Apr-2018
26             15-Apr-2018
27             15-Apr-2018
28             15-Apr-2018
29             15-Apr-2018
Name: Date, dtype: object

In [634]:
#to_date =lambda x:re.sub('.[a-z]|.[A-Z]','',str(x)).strip() 

#remove_r = lambda x: re.sub('Reported','',str(x)).strip()
#remove_s = lambda x: re.sub(' ','-',str(x)).strip()

In [953]:
def change_date(x):
    x =  re.sub('Reported','',str(x)).strip()
    x = re.sub(' ','-',str(x)).strip()
    
    try: 
        x = pd.to_datetime(x)
        return x
    
    except:
        return np.NaN

In [956]:
#df['Year'] = df['Year'].astype(np.int64)

In [954]:
df['Date'] = df['Date'].apply(change_date)

In [970]:
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
Case Number,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04,2018.06.03.b,2018.06.03.a,2018.05.27,2018.05.26.b,2018.05.26.a
Date,2018-06-25 00:00:00,2018-06-18 00:00:00,2018-06-09 00:00:00,2018-06-08 00:00:00,2018-06-04 00:00:00,2018-06-03 00:00:00,2018-06-03 00:00:00,2018-05-27 00:00:00,2018-05-26 00:00:00,2018-05-26 00:00:00
Year,2018.0,2018.0,2018.0,2018.0,2018.0,2018.0,2018.0,2018.0,2018.0,2018.0
Type,Boating,Unprovoked,Invalid,Unprovoked,Provoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked
Country,USA,USA,USA,AUSTRALIA,MEXICO,AUSTRALIA,BRAZIL,USA,USA,USA
Area,California,Georgia,Hawaii,New South Wales,Colima,New South Wales,Pernambuco,Florida,Florida,Florida
Location,"Oceanside, San Diego County","St. Simon Island, Glynn County","Habush, Oahu",Arrawarra Headland,La Ticla,"Flat Rock, Ballina","Piedade Beach, Recife","Lighhouse Point Park, Ponce Inlet, Volusia County","Cocoa Beach, Brevard County","Daytona Beach, Volusia County"
Activity,Paddling,Standing,Surfing,Surfing,Free diving,Kite surfing,Swimming,Fishing,Walking,Standing
Name,Julie Wolfe,AdysonÂ McNeely,John Denges,male,Gustavo Ramos,Chris,Jose Ernesto da Silva,male,Cody High,male
Sex,F,F,M,M,M,M,M,M,M,M
Age,57,11,48,NaN,NaN,NaN,18,52,15,12
Injury,"No injury to occupant, outrigger canoe and pad...",Minor injury to left thigh,Injury to left lower leg from surfboard skeg,Minor injury to lower leg,Lacerations to leg & hand shark PROVOKED INCIDENT,"No injury, board bitten",FATAL,Minor injury to foot. PROVOKED INCIDENT,Lower left leg bitten,Minor injury to foot
Fatal (Y/N),N,N,N,N,N,N,Y,N,N,N
Time,18h00,14h00 -15h00,07h45,NaN,NaN,NaN,Late afternoon,NaN,17h00,14h00
Species,White shark,NaN,NaN,2 m shark,"Tiger shark, 3m",NaN,Tiger shark,"Lemon shark, 3'","Bull shark, 6'",NaN
Investigator or Source,"R. Collier, GSAF","K.McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","B. Myatt, GSAF",A .Kipper,"Daily Telegraph, 6/4/2018","Diario de Pernambuco, 6/4/2018","K. McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","K. McMurray, Tracking Sharks.com"
pdf,2018.06.25-Wolfe.pdf,2018.06.18-McNeely.pdf,2018.06.09-Denges.pdf,2018.06.08-Arrawarra.pdf,2018.06.04-Ramos.pdf,2018.06.03.b-FlatRock.pdf,2018.06.03.a-daSilva.pdf,2018.05.27-Ponce.pdf,2018.05.26.b-High.pdf,2018.05.26.a-DaytonaBeach.pdf
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
original order,6303.0,6302.0,6301.0,6300.0,6299.0,6298.0,6297.0,6296.0,6295.0,6294.0

In [ ]:
# Especial intervention to Original Order

In [959]:
#1 - columnas
#0 - rows

In [966]:
df.drop([6302, 6303,6304,6305,6306,6307,6308], axis = 0, inplace = True)

In [968]:
df.tail(10).T

,6292,6293,6294,6295,6296,6297,6298,6299,6300,6301
Case Number,ND.0010,ND.0009,ND.0008,ND.0007,ND.0006,ND.0005,ND.0004,ND.0003,ND.0002,ND.0001
Date,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
Year,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Type,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked,Unprovoked
Country,USA,AUSTRALIA,AUSTRALIA,AUSTRALIA,AUSTRALIA,AUSTRALIA,AUSTRALIA,USA,PANAMA,CEYLON (SRI LANKA)
Area,Hawaii,NaN,NaN,NaN,New South Wales,Western Australia,Western Australia,North Carolina,NaN,Eastern Province
Location,Puna,NaN,NaN,NaN,,Roebuck Bay,NaN,Ocracoke Inlet,"Panama Bay 8ÂºN, 79ÂºW","Below the English fort, Trincomalee"
Activity,NaN,Fishing,Fishing,Fishing,Swimming,Diving,Pearl diving,Swimming,NaN,Swimming
Name,"A ""chiefess""",boy,fisherman,fisherman,Arab boy,male,Ahmun,Coast Guard personnel,Jules Patterson,male
Sex,F,M,M,M,M,M,M,M,M,M
Age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
Injury,Ankle bitten,"FATAL, knocked overboard by tail of shark & ca...",FATAL,FATAL,FATAL,FATAL,FATAL,FATAL,FATAL,"FATAL. ""Shark bit him in half, carrying away t..."
Fatal (Y/N),N,Y,Y,Y,Y,Y,Y,Y,Y,Y
Time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Species,NaN,Blue pointer,Blue pointer,Blue pointers,Said to involve a grey nurse shark that leapt ...,NaN,NaN,NaN,NaN,NaN
Investigator or Source,Captain W. Young,"NY Sun, 9/9/1906, referring to account by Loui...","NY Sun, 9/9/1906, referring to account by Loui...","NY Sun, 9/9/1906, referring to account by Loui...","L. Becke in New York Sun, 9/9/1906; L. Schultz...","H. Taunton; N. Bartlett, p. 234","H. Taunton; N. Bartlett, pp. 233-234","F. Schwartz, p.23; C. Creswell, GSAF","The Sun, 10/20/1938",S.W. Baker
pdf,ND-0010-Puna Hawaii.pdf,ND-0009-boy-Australia.pdf,ND-0008-Fisherman2-Australia.pdf,ND-0007 - Fisherman-Australia.pdf,ND-0006-ArabBoy-Prymount.pdf,ND-0005-RoebuckBay.pdf,ND-0004-Ahmun.pdf,ND-0003-Ocracoke_1900-1905.pdf,ND-0002-JulesPatterson.pdf,ND-0001-Ceylon.pdf
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
original order,11.0,10.0,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0

In [969]:
df.shape

(6302, 19)

In [961]:
df['original order'].unique()

array([6303., 6302., 6301., ..., 6308., 6309., 6310.])

In [962]:
df.head().T

,0,1,2,3,4
Case Number,2018.06.25,2018.06.18,2018.06.09,2018.06.08,2018.06.04
Date,2018-06-25 00:00:00,2018-06-18 00:00:00,2018-06-09 00:00:00,2018-06-08 00:00:00,2018-06-04 00:00:00
Year,2018.0,2018.0,2018.0,2018.0,2018.0
Type,Boating,Unprovoked,Invalid,Unprovoked,Provoked
Country,USA,USA,USA,AUSTRALIA,MEXICO
Area,California,Georgia,Hawaii,New South Wales,Colima
Location,"Oceanside, San Diego County","St. Simon Island, Glynn County","Habush, Oahu",Arrawarra Headland,La Ticla
Activity,Paddling,Standing,Surfing,Surfing,Free diving
Name,Julie Wolfe,AdysonÂ McNeely,John Denges,male,Gustavo Ramos
Sex,F,F,M,M,M
Age,57,11,48,NaN,NaN
Injury,"No injury to occupant, outrigger canoe and pad...",Minor injury to left thigh,Injury to left lower leg from surfboard skeg,Minor injury to lower leg,Lacerations to leg & hand shark PROVOKED INCIDENT
Fatal (Y/N),N,N,N,N,N
Time,18h00,14h00 -15h00,07h45,NaN,NaN
Species,White shark,NaN,NaN,2 m shark,"Tiger shark, 3m"
Investigator or Source,"R. Collier, GSAF","K.McMurray, TrackingSharks.com","K.McMurray, TrackingSharks.com","B. Myatt, GSAF",A .Kipper
pdf,2018.06.25-Wolfe.pdf,2018.06.18-McNeely.pdf,2018.06.09-Denges.pdf,2018.06.08-Arrawarra.pdf,2018.06.04-Ramos.pdf
href,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
original order,6303.0,6302.0,6301.0,6300.0,6299.0

### Year

In [878]:
df['Year'].unique()

array([2018., 2017.,   nan, 2016., 2015., 2014., 2013., 2012., 2011.,
       2010., 2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002.,
       2001., 2000., 1999., 1998., 1997., 1996., 1995., 1984., 1994.,
       1993., 1992., 1991., 1990., 1989., 1969., 1988., 1987., 1986.,
       1985., 1983., 1982., 1981., 1980., 1979., 1978., 1977., 1976.,
       1975., 1974., 1973., 1972., 1971., 1970., 1968., 1967., 1966.,
       1965., 1964., 1963., 1962., 1961., 1960., 1959., 1958., 1957.,
       1956., 1955., 1954., 1953., 1952., 1951., 1950., 1949., 1948.,
       1848., 1947., 1946., 1945., 1944., 1943., 1942., 1941., 1940.,
       1939., 1938., 1937., 1936., 1935., 1934., 1933., 1932., 1931.,
       1930., 1929., 1928., 1927., 1926., 1925., 1924., 1923., 1922.,
       1921., 1920., 1919., 1918., 1917., 1916., 1915., 1914., 1913.,
       1912., 1911., 1910., 1909., 1908., 1907., 1906., 1905., 1904.,
       1903., 1902., 1901., 1900., 1899., 1898., 1897., 1896., 1895.,
       1894., 1893., 1892., 1891., 1890., 1889., 1888., 1887., 1886.,
       1885., 1884., 1883., 1882., 1881., 1880., 1879., 1878., 1877.,
       1876., 1875., 1874., 1873., 1872., 1871., 1870., 1869., 1868.,
       1867., 1866., 1865., 1864., 1863., 1862., 1861., 1860., 1859.,
       1858., 1857., 1856., 1855., 1853., 1852., 1851., 1850., 1849.,
       1847., 1846., 1845., 1844., 1842., 1841., 1840., 1839., 1837.,
       1836., 1835., 1834., 1832., 1831., 1830., 1829., 1828., 1827.,
       1826., 1825., 1823., 1822., 1819., 1818., 1817., 1816., 1815.,
       1812., 1811., 1810., 1808., 1807., 1805., 1804., 1803., 1802.,
       1801., 1800., 1797., 1792., 1791., 1788., 1787., 1786., 1785.,
       1784., 1783., 1780., 1779., 1776., 1771., 1767., 1764., 1758.,
       1753., 1751., 1749., 1755., 1748., 1742., 1738., 1733., 1723.,
       1721., 1703., 1700., 1642., 1638., 1637., 1617., 1595., 1580.,
       1555., 1554., 1543.,  500.,   77.,    5.,    0.])

In [737]:
df['Year'].head(10)

0    2018.0
1    2018.0
2    2018.0
3    2018.0
4    2018.0
5    2018.0
6    2018.0
7    2018.0
8    2018.0
9    2018.0
Name: Year, dtype: object

In [885]:
def change_year(x):

    if not re.findall('\d{4}',str(x)):
        return np.NaN
    else:
        return x.apply(int)

In [810]:
#df['Year'].apply(change_year)

In [886]:
df['Year'] = df['Year'].apply(change_year)

AttributeError: 'float' object has no attribute 'apply'

In [798]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href,original order
0,2018.06.25,2018-06-25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6303.0
1,2018.06.18,2018-06-18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6302.0
2,2018.06.09,2018-06-09,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6301.0
3,2018.06.08,2018-06-08,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6300.0
4,2018.06.04,2018-06-04,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [439]:
def change_date(date):
    date = re.sub('Reported','',str(date)).strip()
    date = re.sub(' \.','-',date)
    
    try: 
        date = pd.to_datetime(date)
        return date

SyntaxError: unexpected EOF while parsing (1652752161.py, line 7)